### ISSUE TITLE
OOM Error (Allocation on Device) on 12GB VRAM, 64GB RAM

### ISSUE THREAD

**Issue by iamrohitanshu** [filliptm/ComfyUI_FL-SongGen#6]
I'm have the following config:
GPU: RTX 3060 12GB
RAM: 64GB DDR4
Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.6.0
ComfyUI frontend version: 1.35.9
Total VRAM 12287 MB, total RAM 65485 MB
pytorch version: 2.8.0+cu128

I'm getting the OOM error when I try to generate a even a 30sec song using `songgeneration_base_new `model, despite it showing that 10-16 GB VRAM is required. I have also tried the enabling `low_mem`, also have tried to run comfyui on cpu mode as well.
Below is the log:

> You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
> LlamaForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
>   - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
>   - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
>   - If you are not the owner of the model architecture class, please contact the model code owner to update it.
> CausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
>   - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
>   - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
>   - If you are not the owner of the model architecture class, please contact the model code owner to update it.
> You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
> [FL SongGen LowMem] Resizing embedding condition_provider.conditioners.description.output_proj: 153732 -> 151659
> 
> ============================================================
> [FL SongGen Auto Style] ERROR: Generation failed!
> Error: Allocation on device
> Traceback (most recent call last):
>   File "E:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui_fl-songgen\fl_nodes\auto_style.py", line 207, in generate
>     mixed_audio, vocal_audio, bgm_audio = wrapper.generate(
>                                           ^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui_fl-songgen\fl_utils\songgen_wrapper.py", line 127, in generate
>     return self._generate_lowmem(
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui_fl-songgen\fl_utils\songgen_wrapper.py", line 343, in _generate_lowmem
>     audiolm = audiolm.eval().cuda().to(torch.float16)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1369, in to
>     return self._apply(convert)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 928, in _apply
>     module._apply(fn)
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 928, in _apply
>     module._apply(fn)
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 928, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 955, in _apply
>     param_applied = fn(param)
>                     ^^^^^^^^^
>   File "E:\ComfyUI_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1355, in convert
>     return t.to(
>            ^^^^^
> torch.OutOfMemoryError: Allocation on device

**Comment by filliptm** [comment]
This has been fixed in v1.3.0 (commit 5c495e6).

**Fix:** Added a new "ultra" low memory mode specifically designed for systems with limited VRAM (~12GB or less).

**Changes:**
- New `memory_mode` dropdown in Model Loader with options: `auto`, `normal`, `low`, `ultra`
- **Auto mode** (recommended): Automatically detects available VRAM and selects the best mode
- **Ultra mode**: Uses aggressive memory management with ~6GB peak VRAM usage:
  - Aggressive VRAM cleanup before each generation phase
  - Model loaded on CPU first, then transferred to GPU in float16
  - Multiple garbage collection rounds between phases
  - VRAM monitoring and logging during generation

**To use:**
```bash
cd ComfyUI/custom_nodes/ComfyUI_FL-SongGen
git pull
```

Then in ComfyUI:
1. Set `memory_mode` to `ultra` (or `auto` to let it auto-detect)
2. Generate your song - you should see VRAM usage logged in the console

For your RTX 3060 12GB, the `auto` mode should select `ultra` automatically, or you can force it manually. The ultra mode should keep peak VRAM well under 10GB.

**Comment by iamrohitanshu** [comment]
Thank you for your quick action. It's working for me now. :)
